---

- hosts: all
  tasks:

  - name: uninstall docker 
    ansible.builtin.yum:
      name: docker-ce-cli.x86_64
      state: absent

  - name: uninstall containerd
    yum: 
      name: containerd.io.x86_64
      state: absent

  - name: uninstall docker-ce
    yum:
      name: docker-ce.x86_64
      state: absent

  - name: uninstall docker rootless
    yum:
      name: docker-ce-rootless-extras.x86_64
      state: absent
